export type RootStackParamList = {
  Home: { clearFilters?: boolean } | undefined;
  CarDetails: { carId: string; carData?: any };
  SellCar: { carId?: string; adminEdit?: boolean } | undefined;
  About: undefined;
  Login: undefined;
  Signup: undefined;
  ForgotPassword: undefined;
  Profile: undefined;
  AccountSettings: undefined;
  Favorites: undefined;
  MyListings: undefined;
  SellerListings: { sellerId: string; sellerName?: string };
  Services: undefined;
  ServiceApplication: { type: 'broker' | 'logistics' };
  ServiceProfile: { type: 'broker' | 'logistics' };
  ServiceDetails: { provider: any; type: 'broker' | 'logistics' };
  ServiceCart: undefined;
  MyOrders: undefined;
  ProviderOrders: undefined;
  AdminDashboard: undefined;
  AdminManagement: undefined;
  AdminModeration: undefined;
  AdminUserDetail: { targetUid: string };
  SearchResults: { initialQuery: string; initialFilters?: { [key: string]: any } };
  Notifications: undefined;
  NotificationSettings: undefined;
};
